#!/bin/bash

rm -rf ../dominus-build-dev/bundle
meteor build --debug --directory ../dominus-build-dev/ --allow-incompatible-update --architecture os.linux.x86_64
cp ./Dockerfile.build ../dominus-build-dev/Dockerfile
cd ../dominus-build-dev/
rm .git/index
git reset
git add -A .
git commit -m "dev build"
git push
