#!/bin/bash

rm -rf ../dominus-build-prod/bundle
meteor build --directory ../dominus-build-prod/ --allow-incompatible-update --architecture os.linux.x86_64
cp ./Dockerfile.build ../dominus-build-prod/Dockerfile
cd ../dominus-build-prod/
rm .git/index
git reset
git add -A .
git commit -m "prod build"
git push
