myAlertList = [
  {type: 'alert_battleStart', name:'Start of Battle'},
  {type: 'alert_receivedGoldFrom', name:'Received Gold'},
  {type: 'alert_receivedArmy', name:'Received Army'},
  {type: 'alert_addedToChatroom', name:'Added to Chatroom'},
  {type: 'alert_kickedFromChatroom', name:'Kicked from Chatroom'},
  {type: 'alert_chatroomMadeAdmin', name: 'Made Admin of Chatroom'},
  {type: 'alert_chatroomRemovedFromAdmin', name: 'No Longer Chatroom Admin'},
  {type: 'alert_chatroomNowOwner', name: 'Now Owner of Chatroom'},
  {type: 'alert_vassalIsUnderAttack', name: 'Vassal is Under Attack'},
  {type: 'alert_armyFinishedAllMoves', name: 'Army Finished Moving'},
  {type: 'alert_villageDestroyed', name: 'Village Destroyed'},
  {type: 'alert_armyDestroyed', name: 'Army Destroyed'},
  {type: 'alert_lostVassal', name: 'Lost Vassal'},
  {type: 'alert_gainedVassal', name: 'Gained Vassal'},
  {type: 'alert_capturedCapital', name: 'Captured Capital'},
  {type: 'alert_newLord', name: 'New Lord'},
  {type: 'alert_newKingChatroom', name: 'New King Chatroom'},
  {type: 'alert_noLongerDominus', name: 'No Longer Dominus'},
  {type: 'alert_noLongerDominusNewUser', name: 'No Longer Dominus Because New User'},
  {type: 'alert_youAreDominus', name: 'You are Dominus'}
]
